$(document).ready(() => {
    var recipes = [
        {'food' : 'Acai Bowl', 'ingredients' : ['Yogurt', 'Apples','Bananas'],
        'pic' : '../imgs/acai-bowl.jpg', 'description' : 'Blend fruits together. Run the acai packets under warm water for about 10 seconds to let them thaw a bit. Pour in could water and fasten the lid. Start blending on the lowest speed, slowly increasing it. Add 1 to 2 tablespoons lime juice and blend briefly. Pur the smoothie into bowls and top with garnishes of your choice. Serve immediately, or cover and refrigerate for up to 3 days', 'index' : 0},
        {'food' : 'Steak', 'ingredients' : ['Steak'], 'pic' : '../imgs/steak-asparagus.jpg', 'description' : 'Season the steaks on all sides with the salt and pepper. Heat oil in a pan or a skillet over high heat until smoking. Sear the steaks for about a minute to a minute and a half on each side, depending on the thickness of your steak for medium-rare. If you would like your steak rarer or more well-done, cook your steak shorter or longer accordingly. In the same pan, cook the asparagus with salt and pepper until tender but still slightly crunchy. Remove from heat. After the steaks have rested for about 5 minutes, slice, then serve with the asparagus. Enjoy!',
        'index' : 1},
        {'food' : 'Marinara Spaghetti', 'ingredients' : ['Spaghetti'], 'pic' : '../imgs/marinara-spaghetti.jpg', 'description' : ' Cook pasta according to package directions. Drain. Simmer sauce for 3-5 minutes or until warm. Serve sauce over pasta', 'index' : 2}, 
        {'food' : 'Spaghetti and Meatballs', 'ingredients' : ['Spaghetti','Meatballs'], 'pic' : '../imgs/spaghetti-meatballs.jpg', 'description' : ' Brown meatballs until no longer pink on a cast iron pan or skillet, 5-7 minutes. Set aside meatballs. Cook pasta according to package directions. Drain. Simmer sauce for 3-5 minutes or until warm. Add meatballs in to warm up. Serve sauce over pasta', 'index' : 3}, 
        {'food' : 'Baked Meatballs', 'ingredients' : ['Meatballs'], 'pic' : '../imgs/meatballs.jpg', 'description' : 'Preheat oven to 350ºF. Spray a large cookie sheet with cooking spray and place meatballs on cooking sheet. Place in oven for 5-7 minutes or until tender', 'index' : 4}, 
        {'food' : 'Brown Buttered Pasta', 'ingredients' : ['Spaghetti'], 'pic' : '../imgs/butter-pasta.jpg', 'description' : ' Cook pasta according to box directions. While pasta is cooking, place two tablespoons butter in skillet on low heat until brown bits form in butter. Drain pasta and place in pan. Turn to coat with butter', 'index' : 5}, 
        {'food' : 'Spaghetti Aglio e Olio', 'ingredients' : ['Spaghetti', 'Garlic'], 'pic' : '../imgs/spaghetti-aglio.jpg', 'description' : ' Cook pasta according to box directions. While pasta is cooking, place 3 tablespoons olive oil in skillet on low heat. Cut 3 cloves of garlic into thinly-slice slivers. Place in olive oil for 3-5 minutes, or just until barely brown. Drain pasta and place in pan. Turn to coat','index' : 6},
        {'food' : 'Broccoli Beef', 'ingredients' : ['Steak', 'Broccoli'], 'pic' : '../imgs/broccoli-beef.jpg', 'description' : 'In a medium bowl, whisk together soy sauce, chicken stock, honey, vinegar, brown sugar, garlic, sesame oil, cornstarch, Sriracha, ginger, red pepper flakes and 1/4 cup water; set aside. Heat olive oil in a large skillet over medium high heat. Add steak and cook, flipping once, until browned, about 3-4 minutes. Stir in broccoli and soy sauce mixture until tender and slightly thickened, about 3-4 minutes. Serve immediately.', 'index' : 7},
        {'food' : 'Baked Potato', 'ingredients' : ['Potato'], 'pic' : '../imgs/baked-potato.jpg', 'description' : 'Preheat the oven to 425 degrees. Wash and dry the potatoes. Pierce the potato 2-3 times with a fork. Rub oil all over the potatoes. Rub salt all over the potatoes. Place the potatoes on a baking sheet and bake for about 45 minutes. The exact baking time will depend on how large the potatoes are. The potato should be tender inside if you poke a fork into it. Serve with butter, cheese, chives, sour cream and all of your favorite toppings!', 'index' : 8},
        {'food' : 'Cheese and Herb Potato', 'ingredients' : ['Potato', 'Cheese'], 'pic' : '../imgs/cheese-potato.jpg', 'description' : 'Preheat oven to 425°. With a sharp knife, cut each potato crosswise into 1/8-in. slices, leaving slices attached at the bottom. fan potatoes slightly and place in a greased 13x9-in. baking dish. In a small bowl, mix butter, salt and pepper. drizzle over potatoes', 'index' : 9},
        {'food' : 'Bibimbap', 'ingredients' : ['Rice'], 'pic' : '../imgs/bibimbap.jpg', 'description' : 'Stir cucumber pieces with 1/4 cup gochujang paste in a bowl; set aside. Bring about 2 cups of water to a boil in a large nonstick skillet and stir in spinach; cook until spinach is bright green and wilted, 2 to 3 minutes. Drain spinach and squeeze out as much moisture as possible; set spinach aside in a bowl and stir soy sauce into spinach. Heat 1 teaspoon olive oil in large nonstick skillet and cook and stir carrots until softened, about 3 minutes; stir in garlic and cook just until fragrant, about 1 more minute. Stir in cucumber pieces with gochujang paste; sprinkle with red pepper flakes, and set the mixture aside in a bowl. Brown beef in a clean nonstick skillet over medium heat, about 5 minutes per side, and set aside. In a separate nonstick skillet, heat 1 more teaspoon olive oil over medium-low heat and fry the eggs just on one side until yolks are runny but whites are firm, 2 to 4 minutes each. To assemble the dish, divide cooked rice into 4 large serving bowls; top with spinach mixture, a few pieces of beef, and cucumber mixture. Place 1 egg atop each serving. Drizzle each bowl with 1 teaspoon of sesame oil, a sprinkle of sesame seeds, and a small amount of gochujang paste if desired', 'index' : 10},
        {'food' : 'Bread Pudding', 'ingredients' : ['Bread'], 'pic' : '../imgs/bread-pudding.jpg', 'description' : 'Heat oven to 350 degrees. In a small saucepan over low heat, warm milk, butter, vanilla, sugar and salt. Continue cooking just until butter melts; cool. Meanwhile, butter a 4-to-6-cup baking dish and fill it with cubed bread. Add eggs to cooled milk mixture and whisk; pour mixture over bread. Bake for 30 to 45 minutes, or until custard is set but still a little wobbly and edges of bread have browned. Serve warm or at room temperature', 'index' : 11},
        {'food' : 'Banana Split', 'ingredients' : ['Banana'], 'pic' : '../imgs/banana-split.jpg', 'description' : 'In a large saucepan, combine 2 quarts of the water with the brown sugar, cinnamon sticks and star anise and bring to a boil, stirring to dissolve the sugar. Remove from the heat. Add the rum and bananas and let stand for 4 hours. Meanwhile, in a medium saucepan, whisk the remaining 1 cup of water with the granulated sugar, cocoa powder and espresso powder and bring to a boil. Whisk in the cream and simmer over low heat, stirring occasionally, until thickened, about 40 minutes. Stir in the chocolate until melted. Remove from the heat; keep warm. Light a grill. Drain the bananas and pat dry with paper towels. Put the turbinado sugar in a shallow bowl. Cut each banana in half lengthwise; dip each half in the sugar to coat evenly. Grill the bananas over a hot fire until they are richly caramelized, about 1 minute per side. Transfer 2 banana halves to each of 8 bowls. Place 3 scoops of ice cream in each split banana and top with 1/4 cup of the mocha sauce. Dollop whipped cream over the splits, top with the nuts and serve', 'index' : 12},
        {'food' : 'Thai Basil Chicken', 'ingredients' : ['Chicken'], 'pic' : '../imgs/thai-basil-chicken.jpg', 'description' : 'Whisk chicken broth, oyster sauce, soy sauce, fish sauce, white sugar, and brown sugar together in a bowl until well blended. Heat large skillet over high heat. Drizzle in oil. Add chicken and stir fry until it loses its raw color, 2 to 3 minutes. Stir in shallots, garlic, and sliced chilies. Continue cooking on high heat until some of the juices start to caramelize in the bottom of the pan, about 2 or 3 more minutes. Add about a tablespoon of the sauce mixture to the skillet; cook and stir until sauce begins to caramelize, about 1 minute. Pour in the rest of the sauce. Cook and stir until sauce has deglazed the bottom of the pan. Continue to cook until sauce glazes onto the meat, 1 or 2 more minutes. Remove from heat. Stir in basil. Cook and stir until basil is wilted, about 20 seconds. Serve with rice', 'index' : 13},
        {'food' : 'Teriyaki Chicken', 'ingredients' : ['Chicken'], 'pic' : '../imgs/teriyaki-chicken.jpg', 'description' : 'In a small saucepan over low heat, combine the cornstarch, cold water, sugar, soy sauce, vinegar, garlic, ginger and ground black pepper. Let simmer, stirring frequently, until sauce thickens and bubbles. Preheat oven to 425 degrees F (220 degrees C). Place chicken pieces in a lightly greased 9x13 inch baking dish. Brush chicken with the sauce. Turn pieces over, and brush again. Bake in the preheated oven for 30 minutes. Turn pieces over, and bake for another 30 minutes, until no longer pink and juices run clear. Brush with sauce every 10 minutes during cooking', 'index' : 14},
        {'food' : 'Deviled Eggs', 'ingredients' : ['Eggs'], 'pic' : '../imgs/deviled-eggs.jpg', 'description' : 'Place eggs in a single layer in a saucepan and cover with enough water that there\'s 1 1/2 inches of water above the eggs. Heat on high until water begins to boil, then cover, turn the heat to low, and cook for 1 minute. Remove from heat and leave covered for 14 minutes, then rinse under cold water continuously for 1 minute. rack egg shells and carefully peel under cool running water. Gently dry with paper towels. Slice the eggs in half lengthwise, removing yolks to a medium bowl, and placing the whites on a serving platter. Mash the yolks into a fine crumble using a fork. Add mayonnaise, vinegar, mustard, salt, and pepper, and mix well. Evenly disperse heaping teaspoons of the yolk mixture into the egg whites. Sprinkle with paprika and serve', 'index' : 15},
    ];
    localStorage.setItem("recipes", JSON.stringify(recipes));

    var source = $("#recipe-template").html();
    var template = Handlebars.compile(source);
    var parentDiv = $("#recipe-list");

    var ingredients = JSON.parse(localStorage.getItem("ingredients"));
    var included = [];
    for (let i = 0; i < recipes.length; i++) {
        if (ingredients.includes(recipes[i].ingredients[0])) {
            if (!included.includes(recipes[i].ingredients[0])) {
                included.push(recipes[i].ingredients[0]);
                var html = template(recipes[i]);
                parentDiv.append(html);
            } else {
                $('#' + recipes[i].ingredients[0]).append('<div class="testing"> <div class="card" style="margin: 0 auto;"> <img class="card-img-top" src="' + recipes[i].pic + '" alt="Card image cap"> <div class="card-body"> <h5 class="card-title">' +  recipes[i].food +  '</h5> <p class="card-text">' + recipes[i].ingredients + '</p> <a href="./singleRecipe.html?recipe=' + recipes[i].food + '" class="recipe-btn btn btn-primary">Get Recipe</a> </div> </div> </div>');
            }
        }
    }
});